<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-01-17 08:59
=======
# Generated by Django 5.1.5 on 2025-01-17 09:02
>>>>>>> Сидоров_разработка_бэкенда_для_всех_страниц
=======
# Generated by Django 5.1.5 on 2025-01-17 09:00
>>>>>>> Петров_разработка_моделей_сайта

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
            name='indexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
=======
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
>>>>>>> Сидоров_разработка_бэкенда_для_всех_страниц
=======
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('url', models.URLField(blank=True)),
>>>>>>> Петров_разработка_моделей_сайта
            ],
        ),
    ]
